# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PropertyFinder' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PropertyFinder
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'

  

  target 'PropertyFinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PropertyFinder-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PropertyFinder-tvOS

  target 'PropertyFinder-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
